apiVersion: v1
kind: Service
metadata:
  name: frontend-dsi-svc
spec:
  ports:
  - port: 80
  selector:
    app: frontend-dsi
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-dsi-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-dsi
        tier: frontend
    spec:
      containers:
      - name: frontend-dsi
        image: iortizf/frontend-dsi:1.0
        ports:
        - containerPort: 80