apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loan-dsi-db-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loan-dsi-db
        tier: database
    spec:
      containers:
      - name: loan-dsi-db
        image: iortizf/loan-dsi-db:1.0
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: loan_dsi
        - name: PGDATA
          value: /var/lib/postgresql/data/loan
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: loan-db-volume
          mountPath: /var/lib/postgresql/data/loan
      volumes:
        - name: loan-db-volume
          persistentVolumeClaim:
            claimName: loan-dsi-db-pvc