apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-dsi-db-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: customer-dsi-db-pv