apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-dsi-db-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-dsi-db
        tier: database
    spec:
      containers:
      - name: customer-dsi-db
        image: iortizf/customer-dsi-db:1.0
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: customer_dsi
        - name: PGDATA
          value: /var/lib/postgresql/data/customer
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: customer-db-volume
          mountPath: /var/lib/postgresql/data/customer
      volumes:
        - name: customer-db-volume
          persistentVolumeClaim:
            claimName: customer-dsi-db-pvc